version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - ./store:/usr/src/app/store
      - ./images:/usr/src/app/images
    environment:
      - FLASK_ENV=development
